language: ruby
rvm:
- 2.3.0
cache:
- bundler
before_script:
- cp .env.example .env
- psql -c 'create database deploylist_test;' -U postgres
- bundle exec rake db:migrate
script:
- bundle exec rspec
sudo: false
