language: ruby
rvm:
- 2.2.2
cache:
- bundler
before_script:
- cp config/database.example.yml config/database.yml
- cp .env.example .env
- psql -c 'create database deploylist_test;' -U postgres
- bundle exec rake db:migrate
script:
- bundle exec rspec
sudo: false
